services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./node-scripts:/app/node-scripts
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    tty: true